### PR TITLE
Signed APK file added

### PR DESCRIPTION
**Pull request by harshvardhan-takawale**
I have added the apk file in app folder with all the passwords in module-level build.gradle file in response to issue #2.

### CODE REVIEW

**Comment by faruktoptas** [comment]
@harshvardhan-takawale Can you attach the apk file to the issue #2  then add the apk url to README please? It can above Contribute section in readme. (like sample-v0.1.1.apk)

**Comment by harshvardhan-takawale** [comment]
@faruktoptas Sorry I didn't properly understand. Can we talk on some chat? Or even a bit more descriptive review would help.

**Comment by faruktoptas** [comment]
We can chat on gitter. https://gitter.im/faruktoptas/FancyShowCaseView?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by faruktoptas** [comment]
Duplicate of #53

**Pull request closed without merging**
