### PR TITLE
fixes my two issues

### PR DESCRIPTION
**Pull request by MFlisar**
https://github.com/faruktoptas/FancyShowCaseView/issues/17
https://github.com/faruktoptas/FancyShowCaseView/issues/18

### CODE REVIEW

**Comment by faruktoptas** [comment]
@MFlisar thank you for your fast solution :)
Can you please rebase and create a single commit with a commit message that includes all your changes?

**Comment by MFlisar** [comment]
I don't know how to do this (but is there a good reason for that? It's no problem to merge this even if it's split up in a few commits).

I'll add the queue builder tomorrow, then I can delete my repo clone and make a new clean on and check in all changes at once if you want

**Comment by faruktoptas** [comment]
It would be better for a clean commit history. I can rebase it while merging the pull request. You don't need to delete repo and do all this stuff again.

**Comment by faruktoptas** [comment]
Please push your commits to `dev` branch not `master`. I'm sorry I still don't have a contribution guilde. I will add it asap.

**Comment by MFlisar** [comment]
I'll make a new pull request then with the dev branch

**Pull request closed without merging**
