### PR TITLE
update gradle dependency 

### PR DESCRIPTION
**Pull request by tuhinadasgupta**

### CODE REVIEW

**Comment by faruktoptas** [comment]
Can you upgrade build tools too?

**Comment by tuhinadasgupta** [comment]
done

**Comment by faruktoptas** [comment]
Thanks you @tuhinadasgupta .
Latest Android Studio version offers gradle 5.4.1. Why did you upgraded to 5.6.2?

**Comment by tuhinadasgupta** [comment]
@faruktoptas I found that the latest stable version of gradle is 5.6.2 but didn't realize that it's not yet Andriod Studio compatible. Fixed!

**Pull request merged**
