### PR TITLE
adding test on Travis CI

### PR DESCRIPTION
**Pull request by akhilmaskeri**
adding line  - ./gradlew FancyShowCaseViewTest to .travis.yml

### CODE REVIEW

**Comment by faruktoptas** [comment]
You can check build results on travis-ci here: https://travis-ci.org/faruktoptas/FancyShowCaseView/pull_requests
It fails now.

**Comment by faruktoptas** [comment]
The problem is that emulator in android-sdk folder doesn't exist `/home/travis/.travis/functions: line 109: /home/travis/android-sdk-linux/emulator/emulator: No such file or directory`

**Comment by faruktoptas** [comment]
You should add this file to the root of the project:
https://github.com/material-components/material-components-android/blob/master/android-wait-for-emulator

**Comment by akhilmaskeri** [comment]
added x86_64 emulators from android 21 to 27 
one test failing : customView

**Comment by akhilmaskeri** [comment]
CustomView test also fails in my local machine. Do I have to change any settings to pass ?

**Comment by faruktoptas** [comment]
I will fix it in dev branch. You can take the fix from dev branch.

**Comment by faruktoptas** [comment]
@akhilmaskeri  This commit fixes broken tests: https://github.com/faruktoptas/FancyShowCaseView/commit/a578e6ae3bad448f395791844c37060d216794b3

**Comment by faruktoptas** [comment]
@akhilmaskeri do you need any help with this PR? I think it is almost done.

**Comment by faruktoptas** [comment]
Closed due to inactivity. Unit tests are used with CI instead of Espresso tests.

**Pull request closed without merging**
